# Generated by Django 2.0.6 on 2018-06-12 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Captcha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eval_string', models.CharField(max_length=100, unique=True)),
                ('ans', models.CharField(max_length=4)),
                ('img_path', models.CharField(max_length=250)),
            ],
        ),
    ]
